theme: jekyll-theme-cayman
title: [CS340 AI     الذكاء الاصطناعي عال ٣٤٠ ] 
description: [AI Tutorial Notebooks by CCIS @ IMISU   دروس تفاعلية من كلية علوم الحاسب والمعلومات بحامعة الإمام محمد بن سعود]
font:
  normal:
    family: SF Mono
    style: Regular
