theme: jekyll-theme-cayman
title: [CS340 AI Course   مادة عال ٣٤٠ الذاء الاصطناعي] 
description: [AI Tutorial Notebooks by CCIS @ IMISU دروس تفاعلية من كلية علوم الحاسب والمعلومات بحامعة الأمام محمد بن سعود]
